# Generated by Django 2.2.7 on 2021-04-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('hometown', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.TextField()),
                ('crew_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('location', models.CharField(max_length=25)),
                ('astro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_project.Astronaut')),
            ],
        ),
        migrations.AddField(
            model_name='astronaut',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_project.Crew'),
        ),
    ]
