# Generated by Django 2.2.7 on 2021-05-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmessage',
            old_name='astro',
            new_name='astronaut',
        ),
    ]
