# Generated by Django 2.2.7 on 2021-05-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0002_auto_20210506_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='location',
        ),
    ]
